# -*- coding: mbcs -*-
# Created by makepy.py version 0.4.95
# By python version 2.5.1 (r251:54863, May  1 2007, 17:47:05) [MSC v.1310 32 bit (Intel)]
# From type library 'MSPPT.OLB'
# On Sun Mar 29 22:03:16 2009
"""Microsoft PowerPoint 12.0 Object Library"""
makepy_version = '0.4.95'
python_version = 0x20501f0

import win32com.client.CLSIDToClass, pythoncom
import win32com.client.util
from pywintypes import IID
from win32com.client import Dispatch

# The following 3 lines may need tweaking for the particular server
# Candidates are pythoncom.Missing, .Empty and .ArgNotFound
defaultNamedOptArg=pythoncom.Empty
defaultNamedNotOptArg=pythoncom.Empty
defaultUnnamedArg=pythoncom.Empty

CLSID = IID('{91493440-5A91-11CF-8700-00AA0060263B}')
MajorVersion = 2
MinorVersion = 9
LibraryFlags = 8
LCID = 0x0

class constants:
	msoAnimAccumulateAlways       =0x2        # from enum MsoAnimAccumulate
	msoAnimAccumulateNone         =0x1        # from enum MsoAnimAccumulate
	msoAnimAdditiveAddBase        =0x1        # from enum MsoAnimAdditive
	msoAnimAdditiveAddSum         =0x2        # from enum MsoAnimAdditive
	msoAnimAfterEffectDim         =0x1        # from enum MsoAnimAfterEffect
	msoAnimAfterEffectHide        =0x2        # from enum MsoAnimAfterEffect
	msoAnimAfterEffectHideOnNextClick=0x3        # from enum MsoAnimAfterEffect
	msoAnimAfterEffectMixed       =-1         # from enum MsoAnimAfterEffect
	msoAnimAfterEffectNone        =0x0        # from enum MsoAnimAfterEffect
	msoAnimCommandTypeCall        =0x1        # from enum MsoAnimCommandType
	msoAnimCommandTypeEvent       =0x0        # from enum MsoAnimCommandType
	msoAnimCommandTypeVerb        =0x2        # from enum MsoAnimCommandType
	msoAnimDirectionAcross        =0x12       # from enum MsoAnimDirection
	msoAnimDirectionBottom        =0xb        # from enum MsoAnimDirection
	msoAnimDirectionBottomLeft    =0xf        # from enum MsoAnimDirection
	msoAnimDirectionBottomRight   =0xe        # from enum MsoAnimDirection
	msoAnimDirectionCenter        =0x1c       # from enum MsoAnimDirection
	msoAnimDirectionClockwise     =0x15       # from enum MsoAnimDirection
	msoAnimDirectionCounterclockwise=0x16       # from enum MsoAnimDirection
	msoAnimDirectionCycleClockwise=0x2b       # from enum MsoAnimDirection
	msoAnimDirectionCycleCounterclockwise=0x2c       # from enum MsoAnimDirection
	msoAnimDirectionDown          =0x3        # from enum MsoAnimDirection
	msoAnimDirectionDownLeft      =0x9        # from enum MsoAnimDirection
	msoAnimDirectionDownRight     =0x8        # from enum MsoAnimDirection
	msoAnimDirectionFontAllCaps   =0x28       # from enum MsoAnimDirection
	msoAnimDirectionFontBold      =0x23       # from enum MsoAnimDirection
	msoAnimDirectionFontItalic    =0x24       # from enum MsoAnimDirection
	msoAnimDirectionFontShadow    =0x27       # from enum MsoAnimDirection
	msoAnimDirectionFontStrikethrough=0x26       # from enum MsoAnimDirection
	msoAnimDirectionFontUnderline =0x25       # from enum MsoAnimDirection
	msoAnimDirectionGradual       =0x2a       # from enum MsoAnimDirection
	msoAnimDirectionHorizontal    =0x10       # from enum MsoAnimDirection
	msoAnimDirectionHorizontalIn  =0x17       # from enum MsoAnimDirection
	msoAnimDirectionHorizontalOut =0x18       # from enum MsoAnimDirection
	msoAnimDirectionIn            =0x13       # from enum MsoAnimDirection
	msoAnimDirectionInBottom      =0x1f       # from enum MsoAnimDirection
	msoAnimDirectionInCenter      =0x1e       # from enum MsoAnimDirection
	msoAnimDirectionInSlightly    =0x1d       # from enum MsoAnimDirection
	msoAnimDirectionInstant       =0x29       # from enum MsoAnimDirection
	msoAnimDirectionLeft          =0x4        # from enum MsoAnimDirection
	msoAnimDirectionNone          =0x0        # from enum MsoAnimDirection
	msoAnimDirectionOrdinalMask   =0x5        # from enum MsoAnimDirection
	msoAnimDirectionOut           =0x14       # from enum MsoAnimDirection
	msoAnimDirectionOutBottom     =0x22       # from enum MsoAnimDirection
	msoAnimDirectionOutCenter     =0x21       # from enum MsoAnimDirection
	msoAnimDirectionOutSlightly   =0x20       # from enum MsoAnimDirection
	msoAnimDirectionRight         =0x2        # from enum MsoAnimDirection
	msoAnimDirectionSlightly      =0x1b       # from enum MsoAnimDirection
	msoAnimDirectionTop           =0xa        # from enum MsoAnimDirection
	msoAnimDirectionTopLeft       =0xc        # from enum MsoAnimDirection
	msoAnimDirectionTopRight      =0xd        # from enum MsoAnimDirection
	msoAnimDirectionUp            =0x1        # from enum MsoAnimDirection
	msoAnimDirectionUpLeft        =0x6        # from enum MsoAnimDirection
	msoAnimDirectionUpRight       =0x7        # from enum MsoAnimDirection
	msoAnimDirectionVertical      =0x11       # from enum MsoAnimDirection
	msoAnimDirectionVerticalIn    =0x19       # from enum MsoAnimDirection
	msoAnimDirectionVerticalOut   =0x1a       # from enum MsoAnimDirection
	msoAnimEffectAppear           =0x1        # from enum MsoAnimEffect
	msoAnimEffectArcUp            =0x2f       # from enum MsoAnimEffect
	msoAnimEffectAscend           =0x27       # from enum MsoAnimEffect
	msoAnimEffectBlast            =0x40       # from enum MsoAnimEffect
	msoAnimEffectBlinds           =0x3        # from enum MsoAnimEffect
	msoAnimEffectBoldFlash        =0x3f       # from enum MsoAnimEffect
	msoAnimEffectBoldReveal       =0x41       # from enum MsoAnimEffect
	msoAnimEffectBoomerang        =0x19       # from enum MsoAnimEffect
	msoAnimEffectBounce           =0x1a       # from enum MsoAnimEffect
	msoAnimEffectBox              =0x4        # from enum MsoAnimEffect
	msoAnimEffectBrushOnColor     =0x42       # from enum MsoAnimEffect
	msoAnimEffectBrushOnUnderline =0x43       # from enum MsoAnimEffect
	msoAnimEffectCenterRevolve    =0x28       # from enum MsoAnimEffect
	msoAnimEffectChangeFillColor  =0x36       # from enum MsoAnimEffect
	msoAnimEffectChangeFont       =0x37       # from enum MsoAnimEffect
	msoAnimEffectChangeFontColor  =0x38       # from enum MsoAnimEffect
	msoAnimEffectChangeFontSize   =0x39       # from enum MsoAnimEffect
	msoAnimEffectChangeFontStyle  =0x3a       # from enum MsoAnimEffect
	msoAnimEffectChangeLineColor  =0x3c       # from enum MsoAnimEffect
	msoAnimEffectCheckerboard     =0x5        # from enum MsoAnimEffect
	msoAnimEffectCircle           =0x6        # from enum MsoAnimEffect
	msoAnimEffectColorBlend       =0x44       # from enum MsoAnimEffect
	msoAnimEffectColorReveal      =0x1b       # from enum MsoAnimEffect
	msoAnimEffectColorWave        =0x45       # from enum MsoAnimEffect
	msoAnimEffectComplementaryColor=0x46       # from enum MsoAnimEffect
	msoAnimEffectComplementaryColor2=0x47       # from enum MsoAnimEffect
	msoAnimEffectContrastingColor =0x48       # from enum MsoAnimEffect
	msoAnimEffectCrawl            =0x7        # from enum MsoAnimEffect
	msoAnimEffectCredits          =0x1c       # from enum MsoAnimEffect
	msoAnimEffectCustom           =0x0        # from enum MsoAnimEffect
	msoAnimEffectDarken           =0x49       # from enum MsoAnimEffect
	msoAnimEffectDesaturate       =0x4a       # from enum MsoAnimEffect
	msoAnimEffectDescend          =0x2a       # from enum MsoAnimEffect
	msoAnimEffectDiamond          =0x8        # from enum MsoAnimEffect
	msoAnimEffectDissolve         =0x9        # from enum MsoAnimEffect
	msoAnimEffectEaseIn           =0x1d       # from enum MsoAnimEffect
	msoAnimEffectExpand           =0x32       # from enum MsoAnimEffect
	msoAnimEffectFade             =0xa        # from enum MsoAnimEffect
	msoAnimEffectFadedSwivel      =0x29       # from enum MsoAnimEffect
	msoAnimEffectFadedZoom        =0x30       # from enum MsoAnimEffect
	msoAnimEffectFlashBulb        =0x4b       # from enum MsoAnimEffect
	msoAnimEffectFlashOnce        =0xb        # from enum MsoAnimEffect
	msoAnimEffectFlicker          =0x4c       # from enum MsoAnimEffect
	msoAnimEffectFlip             =0x33       # from enum MsoAnimEffect
	msoAnimEffectFloat            =0x1e       # from enum MsoAnimEffect
	msoAnimEffectFly              =0x2        # from enum MsoAnimEffect
	msoAnimEffectFold             =0x35       # from enum MsoAnimEffect
	msoAnimEffectGlide            =0x31       # from enum MsoAnimEffect
	msoAnimEffectGrowAndTurn      =0x1f       # from enum MsoAnimEffect
	msoAnimEffectGrowShrink       =0x3b       # from enum MsoAnimEffect
	msoAnimEffectGrowWithColor    =0x4d       # from enum MsoAnimEffect
	msoAnimEffectLightSpeed       =0x20       # from enum MsoAnimEffect
	msoAnimEffectLighten          =0x4e       # from enum MsoAnimEffect
	msoAnimEffectMediaPause       =0x54       # from enum MsoAnimEffect
	msoAnimEffectMediaPlay        =0x53       # from enum MsoAnimEffect
	msoAnimEffectMediaStop        =0x55       # from enum MsoAnimEffect
	msoAnimEffectPath4PointStar   =0x65       # from enum MsoAnimEffect
	msoAnimEffectPath5PointStar   =0x5a       # from enum MsoAnimEffect
	msoAnimEffectPath6PointStar   =0x60       # from enum MsoAnimEffect
	msoAnimEffectPath8PointStar   =0x66       # from enum MsoAnimEffect
	msoAnimEffectPathArcDown      =0x7a       # from enum MsoAnimEffect
	msoAnimEffectPathArcLeft      =0x88       # from enum MsoAnimEffect
	msoAnimEffectPathArcRight     =0x8f       # from enum MsoAnimEffect
	msoAnimEffectPathArcUp        =0x81       # from enum MsoAnimEffect
	msoAnimEffectPathBean         =0x74       # from enum MsoAnimEffect
	msoAnimEffectPathBounceLeft   =0x7e       # from enum MsoAnimEffect
	msoAnimEffectPathBounceRight  =0x8b       # from enum MsoAnimEffect
	msoAnimEffectPathBuzzsaw      =0x6e       # from enum MsoAnimEffect
	msoAnimEffectPathCircle       =0x56       # from enum MsoAnimEffect
	msoAnimEffectPathCrescentMoon =0x5b       # from enum MsoAnimEffect
	msoAnimEffectPathCurvedSquare =0x69       # from enum MsoAnimEffect
	msoAnimEffectPathCurvedX      =0x6a       # from enum MsoAnimEffect
	msoAnimEffectPathCurvyLeft    =0x85       # from enum MsoAnimEffect
	msoAnimEffectPathCurvyRight   =0x92       # from enum MsoAnimEffect
	msoAnimEffectPathCurvyStar    =0x6c       # from enum MsoAnimEffect
	msoAnimEffectPathDecayingWave =0x91       # from enum MsoAnimEffect
	msoAnimEffectPathDiagonalDownRight=0x86       # from enum MsoAnimEffect
	msoAnimEffectPathDiagonalUpRight=0x8d       # from enum MsoAnimEffect
	msoAnimEffectPathDiamond      =0x58       # from enum MsoAnimEffect
	msoAnimEffectPathDown         =0x7f       # from enum MsoAnimEffect
	msoAnimEffectPathEqualTriangle=0x62       # from enum MsoAnimEffect
	msoAnimEffectPathFigure8Four  =0x71       # from enum MsoAnimEffect
	msoAnimEffectPathFootball     =0x61       # from enum MsoAnimEffect
	msoAnimEffectPathFunnel       =0x89       # from enum MsoAnimEffect
	msoAnimEffectPathHeart        =0x5e       # from enum MsoAnimEffect
	msoAnimEffectPathHeartbeat    =0x82       # from enum MsoAnimEffect
	msoAnimEffectPathHexagon      =0x59       # from enum MsoAnimEffect
	msoAnimEffectPathHorizontalFigure8=0x6f       # from enum MsoAnimEffect
	msoAnimEffectPathInvertedSquare=0x77       # from enum MsoAnimEffect
	msoAnimEffectPathInvertedTriangle=0x76       # from enum MsoAnimEffect
	msoAnimEffectPathLeft         =0x78       # from enum MsoAnimEffect
	msoAnimEffectPathLoopdeLoop   =0x6d       # from enum MsoAnimEffect
	msoAnimEffectPathNeutron      =0x72       # from enum MsoAnimEffect
	msoAnimEffectPathOctagon      =0x5f       # from enum MsoAnimEffect
	msoAnimEffectPathParallelogram=0x63       # from enum MsoAnimEffect
	msoAnimEffectPathPeanut       =0x70       # from enum MsoAnimEffect
	msoAnimEffectPathPentagon     =0x64       # from enum MsoAnimEffect
	msoAnimEffectPathPlus         =0x75       # from enum MsoAnimEffect
	msoAnimEffectPathPointyStar   =0x68       # from enum MsoAnimEffect
	msoAnimEffectPathRight        =0x95       # from enum MsoAnimEffect
	msoAnimEffectPathRightTriangle=0x57       # from enum MsoAnimEffect
	msoAnimEffectPathSCurve1      =0x90       # from enum MsoAnimEffect
	msoAnimEffectPathSCurve2      =0x7c       # from enum MsoAnimEffect
	msoAnimEffectPathSineWave     =0x7d       # from enum MsoAnimEffect
	msoAnimEffectPathSpiralLeft   =0x8c       # from enum MsoAnimEffect
	msoAnimEffectPathSpiralRight  =0x83       # from enum MsoAnimEffect
	msoAnimEffectPathSpring       =0x8a       # from enum MsoAnimEffect
	msoAnimEffectPathSquare       =0x5c       # from enum MsoAnimEffect
	msoAnimEffectPathStairsDown   =0x93       # from enum MsoAnimEffect
	msoAnimEffectPathSwoosh       =0x73       # from enum MsoAnimEffect
	msoAnimEffectPathTeardrop     =0x67       # from enum MsoAnimEffect
	msoAnimEffectPathTrapezoid    =0x5d       # from enum MsoAnimEffect
	msoAnimEffectPathTurnDown     =0x87       # from enum MsoAnimEffect
	msoAnimEffectPathTurnRight    =0x79       # from enum MsoAnimEffect
	msoAnimEffectPathTurnUp       =0x80       # from enum MsoAnimEffect
	msoAnimEffectPathTurnUpRight  =0x8e       # from enum MsoAnimEffect
	msoAnimEffectPathUp           =0x94       # from enum MsoAnimEffect
	msoAnimEffectPathVerticalFigure8=0x6b       # from enum MsoAnimEffect
	msoAnimEffectPathWave         =0x84       # from enum MsoAnimEffect
	msoAnimEffectPathZigzag       =0x7b       # from enum MsoAnimEffect
	msoAnimEffectPeek             =0xc        # from enum MsoAnimEffect
	msoAnimEffectPinwheel         =0x21       # from enum MsoAnimEffect
	msoAnimEffectPlus             =0xd        # from enum MsoAnimEffect
	msoAnimEffectRandomBars       =0xe        # from enum MsoAnimEffect
	msoAnimEffectRandomEffects    =0x18       # from enum MsoAnimEffect
	msoAnimEffectRiseUp           =0x22       # from enum MsoAnimEffect
	msoAnimEffectShimmer          =0x34       # from enum MsoAnimEffect
	msoAnimEffectSling            =0x2b       # from enum MsoAnimEffect
	msoAnimEffectSpin             =0x3d       # from enum MsoAnimEffect
	msoAnimEffectSpinner          =0x2c       # from enum MsoAnimEffect
	msoAnimEffectSpiral           =0xf        # from enum MsoAnimEffect
	msoAnimEffectSplit            =0x10       # from enum MsoAnimEffect
	msoAnimEffectStretch          =0x11       # from enum MsoAnimEffect
	msoAnimEffectStretchy         =0x2d       # from enum MsoAnimEffect
	msoAnimEffectStrips           =0x12       # from enum MsoAnimEffect
	msoAnimEffectStyleEmphasis    =0x4f       # from enum MsoAnimEffect
	msoAnimEffectSwish            =0x23       # from enum MsoAnimEffect
	msoAnimEffectSwivel           =0x13       # from enum MsoAnimEffect
	msoAnimEffectTeeter           =0x50       # from enum MsoAnimEffect
	msoAnimEffectThinLine         =0x24       # from enum MsoAnimEffect
	msoAnimEffectTransparency     =0x3e       # from enum MsoAnimEffect
	msoAnimEffectUnfold           =0x25       # from enum MsoAnimEffect
	msoAnimEffectVerticalGrow     =0x51       # from enum MsoAnimEffect
	msoAnimEffectWave             =0x52       # from enum MsoAnimEffect
	msoAnimEffectWedge            =0x14       # from enum MsoAnimEffect
	msoAnimEffectWheel            =0x15       # from enum MsoAnimEffect
	msoAnimEffectWhip             =0x26       # from enum MsoAnimEffect
	msoAnimEffectWipe             =0x16       # from enum MsoAnimEffect
	msoAnimEffectZip              =0x2e       # from enum MsoAnimEffect
	msoAnimEffectZoom             =0x17       # from enum MsoAnimEffect
	msoAnimEffectAfterFreeze      =0x1        # from enum MsoAnimEffectAfter
	msoAnimEffectAfterHold        =0x3        # from enum MsoAnimEffectAfter
	msoAnimEffectAfterRemove      =0x2        # from enum MsoAnimEffectAfter
	msoAnimEffectAfterTransition  =0x4        # from enum MsoAnimEffectAfter
	msoAnimEffectRestartAlways    =0x1        # from enum MsoAnimEffectRestart
	msoAnimEffectRestartNever     =0x3        # from enum MsoAnimEffectRestart
	msoAnimEffectRestartWhenOff   =0x2        # from enum MsoAnimEffectRestart
	msoAnimFilterEffectSubtypeAcross=0x9        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeDown=0x19       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeDownLeft=0xe        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeDownRight=0x10       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeFromBottom=0xd        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeFromLeft=0xa        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeFromRight=0xb        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeFromTop=0xc        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeHorizontal=0x5        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeIn  =0x7        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeInHorizontal=0x3        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeInVertical=0x1        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeLeft=0x17       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeNone=0x0        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeOut =0x8        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeOutHorizontal=0x4        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeOutVertical=0x2        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeRight=0x18       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeSpokes1=0x12       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeSpokes2=0x13       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeSpokes3=0x14       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeSpokes4=0x15       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeSpokes8=0x16       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeUp  =0x1a       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeUpLeft=0xf        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeUpRight=0x11       # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectSubtypeVertical=0x6        # from enum MsoAnimFilterEffectSubtype
	msoAnimFilterEffectTypeBarn   =0x1        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeBlinds =0x2        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeBox    =0x3        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeCheckerboard=0x4        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeCircle =0x5        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeDiamond=0x6        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeDissolve=0x7        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeFade   =0x8        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeImage  =0x9        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeNone   =0x0        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypePixelate=0xa        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypePlus   =0xb        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeRandomBar=0xc        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeSlide  =0xd        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeStretch=0xe        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeStrips =0xf        # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeWedge  =0x10       # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeWheel  =0x11       # from enum MsoAnimFilterEffectType
	msoAnimFilterEffectTypeWipe   =0x12       # from enum MsoAnimFilterEffectType
	msoAnimColor                  =0x7        # from enum MsoAnimProperty
	msoAnimHeight                 =0x4        # from enum MsoAnimProperty
	msoAnimNone                   =0x0        # from enum MsoAnimProperty
	msoAnimOpacity                =0x5        # from enum MsoAnimProperty
	msoAnimRotation               =0x6        # from enum MsoAnimProperty
	msoAnimShapeFillBackColor     =0x3ef      # from enum MsoAnimProperty
	msoAnimShapeFillColor         =0x3ed      # from enum MsoAnimProperty
	msoAnimShapeFillOn            =0x3ec      # from enum MsoAnimProperty
	msoAnimShapeFillOpacity       =0x3ee      # from enum MsoAnimProperty
	msoAnimShapeLineColor         =0x3f1      # from enum MsoAnimProperty
	msoAnimShapeLineOn            =0x3f0      # from enum MsoAnimProperty
	msoAnimShapePictureBrightness =0x3e9      # from enum MsoAnimProperty
	msoAnimShapePictureContrast   =0x3e8      # from enum MsoAnimProperty
	msoAnimShapePictureGamma      =0x3ea      # from enum MsoAnimProperty
	msoAnimShapePictureGrayscale  =0x3eb      # from enum MsoAnimProperty
	msoAnimShapeShadowColor       =0x3f4      # from enum MsoAnimProperty
	msoAnimShapeShadowOffsetX     =0x3f6      # from enum MsoAnimProperty
	msoAnimShapeShadowOffsetY     =0x3f7      # from enum MsoAnimProperty
	msoAnimShapeShadowOn          =0x3f2      # from enum MsoAnimProperty
	msoAnimShapeShadowOpacity     =0x3f5      # from enum MsoAnimProperty
	msoAnimShapeShadowType        =0x3f3      # from enum MsoAnimProperty
	msoAnimTextBulletCharacter    =0x6f       # from enum MsoAnimProperty
	msoAnimTextBulletColor        =0x72       # from enum MsoAnimProperty
	msoAnimTextBulletFontName     =0x70       # from enum MsoAnimProperty
	msoAnimTextBulletNumber       =0x71       # from enum MsoAnimProperty
	msoAnimTextBulletRelativeSize =0x73       # from enum MsoAnimProperty
	msoAnimTextBulletStyle        =0x74       # from enum MsoAnimProperty
	msoAnimTextBulletType         =0x75       # from enum MsoAnimProperty
	msoAnimTextFontBold           =0x64       # from enum MsoAnimProperty
	msoAnimTextFontColor          =0x65       # from enum MsoAnimProperty
	msoAnimTextFontEmboss         =0x66       # from enum MsoAnimProperty
	msoAnimTextFontItalic         =0x67       # from enum MsoAnimProperty
	msoAnimTextFontName           =0x68       # from enum MsoAnimProperty
	msoAnimTextFontShadow         =0x69       # from enum MsoAnimProperty
	msoAnimTextFontSize           =0x6a       # from enum MsoAnimProperty
	msoAnimTextFontStrikeThrough  =0x6e       # from enum MsoAnimProperty
	msoAnimTextFontSubscript      =0x6b       # from enum MsoAnimProperty
	msoAnimTextFontSuperscript    =0x6c       # from enum MsoAnimProperty
	msoAnimTextFontUnderline      =0x6d       # from enum MsoAnimProperty
	msoAnimVisibility             =0x8        # from enum MsoAnimProperty
	msoAnimWidth                  =0x3        # from enum MsoAnimProperty
	msoAnimX                      =0x1        # from enum MsoAnimProperty
	msoAnimY                      =0x2        # from enum MsoAnimProperty
	msoAnimTextUnitEffectByCharacter=0x1        # from enum MsoAnimTextUnitEffect
	msoAnimTextUnitEffectByParagraph=0x0        # from enum MsoAnimTextUnitEffect
	msoAnimTextUnitEffectByWord   =0x2        # from enum MsoAnimTextUnitEffect
	msoAnimTextUnitEffectMixed    =-1         # from enum MsoAnimTextUnitEffect
	msoAnimTriggerAfterPrevious   =0x3        # from enum MsoAnimTriggerType
	msoAnimTriggerMixed           =-1         # from enum MsoAnimTriggerType
	msoAnimTriggerNone            =0x0        # from enum MsoAnimTriggerType
	msoAnimTriggerOnPageClick     =0x1        # from enum MsoAnimTriggerType
	msoAnimTriggerOnShapeClick    =0x4        # from enum MsoAnimTriggerType
	msoAnimTriggerWithPrevious    =0x2        # from enum MsoAnimTriggerType
	msoAnimTypeColor              =0x2        # from enum MsoAnimType
	msoAnimTypeCommand            =0x6        # from enum MsoAnimType
	msoAnimTypeFilter             =0x7        # from enum MsoAnimType
	msoAnimTypeMixed              =-2         # from enum MsoAnimType
	msoAnimTypeMotion             =0x1        # from enum MsoAnimType
	msoAnimTypeNone               =0x0        # from enum MsoAnimType
	msoAnimTypeProperty           =0x5        # from enum MsoAnimType
	msoAnimTypeRotation           =0x4        # from enum MsoAnimType
	msoAnimTypeScale              =0x3        # from enum MsoAnimType
	msoAnimTypeSet                =0x8        # from enum MsoAnimType
	msoAnimateChartAllAtOnce      =0x7        # from enum MsoAnimateByLevel
	msoAnimateChartByCategory     =0x8        # from enum MsoAnimateByLevel
	msoAnimateChartByCategoryElements=0x9        # from enum MsoAnimateByLevel
	msoAnimateChartBySeries       =0xa        # from enum MsoAnimateByLevel
	msoAnimateChartBySeriesElements=0xb        # from enum MsoAnimateByLevel
	msoAnimateDiagramAllAtOnce    =0xc        # from enum MsoAnimateByLevel
	msoAnimateDiagramBreadthByLevel=0x10       # from enum MsoAnimateByLevel
	msoAnimateDiagramBreadthByNode=0xf        # from enum MsoAnimateByLevel
	msoAnimateDiagramClockwise    =0x11       # from enum MsoAnimateByLevel
	msoAnimateDiagramClockwiseIn  =0x12       # from enum MsoAnimateByLevel
	msoAnimateDiagramClockwiseOut =0x13       # from enum MsoAnimateByLevel
	msoAnimateDiagramCounterClockwise=0x14       # from enum MsoAnimateByLevel
	msoAnimateDiagramCounterClockwiseIn=0x15       # from enum MsoAnimateByLevel
	msoAnimateDiagramCounterClockwiseOut=0x16       # from enum MsoAnimateByLevel
	msoAnimateDiagramDepthByBranch=0xe        # from enum MsoAnimateByLevel
	msoAnimateDiagramDepthByNode  =0xd        # from enum MsoAnimateByLevel
	msoAnimateDiagramDown         =0x1a       # from enum MsoAnimateByLevel
	msoAnimateDiagramInByRing     =0x17       # from enum MsoAnimateByLevel
	msoAnimateDiagramOutByRing    =0x18       # from enum MsoAnimateByLevel
	msoAnimateDiagramUp           =0x19       # from enum MsoAnimateByLevel
	msoAnimateLevelMixed          =-1         # from enum MsoAnimateByLevel
	msoAnimateLevelNone           =0x0        # from enum MsoAnimateByLevel
	msoAnimateTextByAllLevels     =0x1        # from enum MsoAnimateByLevel
	msoAnimateTextByFifthLevel    =0x6        # from enum MsoAnimateByLevel
	msoAnimateTextByFirstLevel    =0x2        # from enum MsoAnimateByLevel
	msoAnimateTextByFourthLevel   =0x5        # from enum MsoAnimateByLevel
	msoAnimateTextBySecondLevel   =0x3        # from enum MsoAnimateByLevel
	msoAnimateTextByThirdLevel    =0x4        # from enum MsoAnimateByLevel
	msoClickStateAfterAllAnimations=-2         # from enum MsoClickState
	msoClickStateBeforeAutomaticAnimations=-1         # from enum MsoClickState
	ppActionEndShow               =0x6        # from enum PpActionType
	ppActionFirstSlide            =0x3        # from enum PpActionType
	ppActionHyperlink             =0x7        # from enum PpActionType
	ppActionLastSlide             =0x4        # from enum PpActionType
	ppActionLastSlideViewed       =0x5        # from enum PpActionType
	ppActionMixed                 =-2         # from enum PpActionType
	ppActionNamedSlideShow        =0xa        # from enum PpActionType
	ppActionNextSlide             =0x1        # from enum PpActionType
	ppActionNone                  =0x0        # from enum PpActionType
	ppActionOLEVerb               =0xb        # from enum PpActionType
	ppActionPlay                  =0xc        # from enum PpActionType
	ppActionPreviousSlide         =0x2        # from enum PpActionType
	ppActionRunMacro              =0x8        # from enum PpActionType
	ppActionRunProgram            =0x9        # from enum PpActionType
	ppAdvanceModeMixed            =-2         # from enum PpAdvanceMode
	ppAdvanceOnClick              =0x1        # from enum PpAdvanceMode
	ppAdvanceOnTime               =0x2        # from enum PpAdvanceMode
	ppAfterEffectDim              =0x2        # from enum PpAfterEffect
	ppAfterEffectHide             =0x1        # from enum PpAfterEffect
	ppAfterEffectHideOnClick      =0x3        # from enum PpAfterEffect
	ppAfterEffectMixed            =-2         # from enum PpAfterEffect
	ppAfterEffectNothing          =0x0        # from enum PpAfterEffect
	ppAlertsAll                   =0x2        # from enum PpAlertLevel
	ppAlertsNone                  =0x1        # from enum PpAlertLevel
	ppArrangeCascade              =0x2        # from enum PpArrangeStyle
	ppArrangeTiled                =0x1        # from enum PpArrangeStyle
	ppAutoSizeMixed               =-2         # from enum PpAutoSize
	ppAutoSizeNone                =0x0        # from enum PpAutoSize
	ppAutoSizeShapeToFitText      =0x1        # from enum PpAutoSize
	ppBaselineAlignAuto           =0x5        # from enum PpBaselineAlignment
	ppBaselineAlignBaseline       =0x1        # from enum PpBaselineAlignment
	ppBaselineAlignCenter         =0x3        # from enum PpBaselineAlignment
	ppBaselineAlignFarEast50      =0x4        # from enum PpBaselineAlignment
	ppBaselineAlignMixed          =-2         # from enum PpBaselineAlignment
	ppBaselineAlignTop            =0x2        # from enum PpBaselineAlignment
	ppBorderBottom                =0x3        # from enum PpBorderType
	ppBorderDiagonalDown          =0x5        # from enum PpBorderType
	ppBorderDiagonalUp            =0x6        # from enum PpBorderType
	ppBorderLeft                  =0x2        # from enum PpBorderType
	ppBorderRight                 =0x4        # from enum PpBorderType
	ppBorderTop                   =0x1        # from enum PpBorderType
	ppBulletMixed                 =-2         # from enum PpBulletType
	ppBulletNone                  =0x0        # from enum PpBulletType
	ppBulletNumbered              =0x2        # from enum PpBulletType
	ppBulletPicture               =0x3        # from enum PpBulletType
	ppBulletUnnumbered            =0x1        # from enum PpBulletType
	ppCaseLower                   =0x2        # from enum PpChangeCase
	ppCaseSentence                =0x1        # from enum PpChangeCase
	ppCaseTitle                   =0x4        # from enum PpChangeCase
	ppCaseToggle                  =0x5        # from enum PpChangeCase
	ppCaseUpper                   =0x3        # from enum PpChangeCase
	ppAnimateByCategory           =0x2        # from enum PpChartUnitEffect
	ppAnimateByCategoryElements   =0x4        # from enum PpChartUnitEffect
	ppAnimateBySeries             =0x1        # from enum PpChartUnitEffect
	ppAnimateBySeriesElements     =0x3        # from enum PpChartUnitEffect
	ppAnimateChartAllAtOnce       =0x5        # from enum PpChartUnitEffect
	ppAnimateChartMixed           =-2         # from enum PpChartUnitEffect
	ppCheckInMajorVersion         =0x1        # from enum PpCheckInVersionType
	ppCheckInMinorVersion         =0x0        # from enum PpCheckInVersionType
	ppCheckInOverwriteVersion     =0x2        # from enum PpCheckInVersionType
	ppAccent1                     =0x6        # from enum PpColorSchemeIndex
	ppAccent2                     =0x7        # from enum PpColorSchemeIndex
	ppAccent3                     =0x8        # from enum PpColorSchemeIndex
	ppBackground                  =0x1        # from enum PpColorSchemeIndex
	ppFill                        =0x5        # from enum PpColorSchemeIndex
	ppForeground                  =0x2        # from enum PpColorSchemeIndex
	ppNotSchemeColor              =0x0        # from enum PpColorSchemeIndex
	ppSchemeColorMixed            =-2         # from enum PpColorSchemeIndex
	ppShadow                      =0x3        # from enum PpColorSchemeIndex
	ppTitle                       =0x4        # from enum PpColorSchemeIndex
	ppDateTimeFigureOut           =0xe        # from enum PpDateTimeFormat
	ppDateTimeFormatMixed         =-2         # from enum PpDateTimeFormat
	ppDateTimeHmm                 =0xa        # from enum PpDateTimeFormat
	ppDateTimeHmmss               =0xb        # from enum PpDateTimeFormat
	ppDateTimeMMMMdyyyy           =0x4        # from enum PpDateTimeFormat
	ppDateTimeMMMMyy              =0x6        # from enum PpDateTimeFormat
	ppDateTimeMMddyyHmm           =0x8        # from enum PpDateTimeFormat
	ppDateTimeMMddyyhmmAMPM       =0x9        # from enum PpDateTimeFormat
	ppDateTimeMMyy                =0x7        # from enum PpDateTimeFormat
	ppDateTimeMdyy                =0x1        # from enum PpDateTimeFormat
	ppDateTimedMMMMyyyy           =0x3        # from enum PpDateTimeFormat
	ppDateTimedMMMyy              =0x5        # from enum PpDateTimeFormat
	ppDateTimeddddMMMMddyyyy      =0x2        # from enum PpDateTimeFormat
	ppDateTimehmmAMPM             =0xc        # from enum PpDateTimeFormat
	ppDateTimehmmssAMPM           =0xd        # from enum PpDateTimeFormat
	ppDirectionLeftToRight        =0x1        # from enum PpDirection
	ppDirectionMixed              =-2         # from enum PpDirection
	ppDirectionRightToLeft        =0x2        # from enum PpDirection
	ppEffectAppear                =0xf04      # from enum PpEntryEffect
	ppEffectBlindsHorizontal      =0x301      # from enum PpEntryEffect
	ppEffectBlindsVertical        =0x302      # from enum PpEntryEffect
	ppEffectBoxIn                 =0xc02      # from enum PpEntryEffect
	ppEffectBoxOut                =0xc01      # from enum PpEntryEffect
	ppEffectCheckerboardAcross    =0x401      # from enum PpEntryEffect
	ppEffectCheckerboardDown      =0x402      # from enum PpEntryEffect
	ppEffectCircleOut             =0xf05      # from enum PpEntryEffect
	ppEffectCombHorizontal        =0xf07      # from enum PpEntryEffect
	ppEffectCombVertical          =0xf08      # from enum PpEntryEffect
	ppEffectCoverDown             =0x504      # from enum PpEntryEffect
	ppEffectCoverLeft             =0x501      # from enum PpEntryEffect
	ppEffectCoverLeftDown         =0x507      # from enum PpEntryEffect
	ppEffectCoverLeftUp           =0x505      # from enum PpEntryEffect
	ppEffectCoverRight            =0x503      # from enum PpEntryEffect
	ppEffectCoverRightDown        =0x508      # from enum PpEntryEffect
	ppEffectCoverRightUp          =0x506      # from enum PpEntryEffect
	ppEffectCoverUp               =0x502      # from enum PpEntryEffect
	ppEffectCrawlFromDown         =0xd10      # from enum PpEntryEffect
	ppEffectCrawlFromLeft         =0xd0d      # from enum PpEntryEffect
	ppEffectCrawlFromRight        =0xd0f      # from enum PpEntryEffect
	ppEffectCrawlFromUp           =0xd0e      # from enum PpEntryEffect
	ppEffectCut                   =0x101      # from enum PpEntryEffect
	ppEffectCutThroughBlack       =0x102      # from enum PpEntryEffect
	ppEffectDiamondOut            =0xf06      # from enum PpEntryEffect
	ppEffectDissolve              =0x601      # from enum PpEntryEffect
	ppEffectFade                  =0x701      # from enum PpEntryEffect
	ppEffectFadeSmoothly          =0xf09      # from enum PpEntryEffect
	ppEffectFlashOnceFast         =0xf01      # from enum PpEntryEffect
	ppEffectFlashOnceMedium       =0xf02      # from enum PpEntryEffect
	ppEffectFlashOnceSlow         =0xf03      # from enum PpEntryEffect
	ppEffectFlyFromBottom         =0xd04      # from enum PpEntryEffect
	ppEffectFlyFromBottomLeft     =0xd07      # from enum PpEntryEffect
	ppEffectFlyFromBottomRight    =0xd08      # from enum PpEntryEffect
	ppEffectFlyFromLeft           =0xd01      # from enum PpEntryEffect
	ppEffectFlyFromRight          =0xd03      # from enum PpEntryEffect
	ppEffectFlyFromTop            =0xd02      # from enum PpEntryEffect
	ppEffectFlyFromTopLeft        =0xd05      # from enum PpEntryEffect
	ppEffectFlyFromTopRight       =0xd06      # from enum PpEntryEffect
	ppEffectMixed                 =-2         # from enum PpEntryEffect
	ppEffectNewsflash             =0xf0a      # from enum PpEntryEffect
	ppEffectNone                  =0x0        # from enum PpEntryEffect
	ppEffectPeekFromDown          =0xd0a      # from enum PpEntryEffect
	ppEffectPeekFromLeft          =0xd09      # from enum PpEntryEffect
	ppEffectPeekFromRight         =0xd0b      # from enum PpEntryEffect
	ppEffectPeekFromUp            =0xd0c      # from enum PpEntryEffect
	ppEffectPlusOut               =0xf0b      # from enum PpEntryEffect
	ppEffectPushDown              =0xf0c      # from enum PpEntryEffect
	ppEffectPushLeft              =0xf0d      # from enum PpEntryEffect
	ppEffectPushRight             =0xf0e      # from enum PpEntryEffect
	ppEffectPushUp                =0xf0f      # from enum PpEntryEffect
	ppEffectRandom                =0x201      # from enum PpEntryEffect
	ppEffectRandomBarsHorizontal  =0x901      # from enum PpEntryEffect
	ppEffectRandomBarsVertical    =0x902      # from enum PpEntryEffect
	ppEffectSpiral                =0xd1d      # from enum PpEntryEffect
	ppEffectSplitHorizontalIn     =0xe02      # from enum PpEntryEffect
	ppEffectSplitHorizontalOut    =0xe01      # from enum PpEntryEffect
	ppEffectSplitVerticalIn       =0xe04      # from enum PpEntryEffect
	ppEffectSplitVerticalOut      =0xe03      # from enum PpEntryEffect
	ppEffectStretchAcross         =0xd17      # from enum PpEntryEffect
	ppEffectStretchDown           =0xd1b      # from enum PpEntryEffect
	ppEffectStretchLeft           =0xd18      # from enum PpEntryEffect
	ppEffectStretchRight          =0xd1a      # from enum PpEntryEffect
	ppEffectStretchUp             =0xd19      # from enum PpEntryEffect
	ppEffectStripsDownLeft        =0xa03      # from enum PpEntryEffect
	ppEffectStripsDownRight       =0xa04      # from enum PpEntryEffect
	ppEffectStripsLeftDown        =0xa07      # from enum PpEntryEffect
	ppEffectStripsLeftUp          =0xa05      # from enum PpEntryEffect
	ppEffectStripsRightDown       =0xa08      # from enum PpEntryEffect
	ppEffectStripsRightUp         =0xa06      # from enum PpEntryEffect
	ppEffectStripsUpLeft          =0xa01      # from enum PpEntryEffect
	ppEffectStripsUpRight         =0xa02      # from enum PpEntryEffect
	ppEffectSwivel                =0xd1c      # from enum PpEntryEffect
	ppEffectUncoverDown           =0x804      # from enum PpEntryEffect
	ppEffectUncoverLeft           =0x801      # from enum PpEntryEffect
	ppEffectUncoverLeftDown       =0x807      # from enum PpEntryEffect
	ppEffectUncoverLeftUp         =0x805      # from enum PpEntryEffect
	ppEffectUncoverRight          =0x803      # from enum PpEntryEffect
	ppEffectUncoverRightDown      =0x808      # from enum PpEntryEffect
	ppEffectUncoverRightUp        =0x806      # from enum PpEntryEffect
	ppEffectUncoverUp             =0x802      # from enum PpEntryEffect
	ppEffectWedge                 =0xf10      # from enum PpEntryEffect
	ppEffectWheel1Spoke           =0xf11      # from enum PpEntryEffect
	ppEffectWheel2Spokes          =0xf12      # from enum PpEntryEffect
	ppEffectWheel3Spokes          =0xf13      # from enum PpEntryEffect
	ppEffectWheel4Spokes          =0xf14      # from enum PpEntryEffect
	ppEffectWheel8Spokes          =0xf15      # from enum PpEntryEffect
	ppEffectWipeDown              =0xb04      # from enum PpEntryEffect
	ppEffectWipeLeft              =0xb01      # from enum PpEntryEffect
	ppEffectWipeRight             =0xb03      # from enum PpEntryEffect
	ppEffectWipeUp                =0xb02      # from enum PpEntryEffect
	ppEffectZoomBottom            =0xd16      # from enum PpEntryEffect
	ppEffectZoomCenter            =0xd15      # from enum PpEntryEffect
	ppEffectZoomIn                =0xd11      # from enum PpEntryEffect
	ppEffectZoomInSlightly        =0xd12      # from enum PpEntryEffect
	ppEffectZoomOut               =0xd13      # from enum PpEntryEffect
	ppEffectZoomOutSlightly       =0xd14      # from enum PpEntryEffect
	ppClipRelativeToSlide         =0x2        # from enum PpExportMode
	ppRelativeToSlide             =0x1        # from enum PpExportMode
	ppScaleToFit                  =0x3        # from enum PpExportMode
	ppScaleXY                     =0x4        # from enum PpExportMode
	ppFarEastLineBreakLevelCustom =0x3        # from enum PpFarEastLineBreakLevel
	ppFarEastLineBreakLevelNormal =0x1        # from enum PpFarEastLineBreakLevel
	ppFarEastLineBreakLevelStrict =0x2        # from enum PpFarEastLineBreakLevel
	ppFileDialogOpen              =0x1        # from enum PpFileDialogType
	ppFileDialogSave              =0x2        # from enum PpFileDialogType
	ppFixedFormatIntentPrint      =0x2        # from enum PpFixedFormatIntent
	ppFixedFormatIntentScreen     =0x1        # from enum PpFixedFormatIntent
	ppFixedFormatTypePDF          =0x2        # from enum PpFixedFormatType
	ppFixedFormatTypeXPS          =0x1        # from enum PpFixedFormatType
	ppFollowColorsMixed           =-2         # from enum PpFollowColors
	ppFollowColorsNone            =0x0        # from enum PpFollowColors
	ppFollowColorsScheme          =0x1        # from enum PpFollowColors
	ppFollowColorsTextAndBackground=0x2        # from enum PpFollowColors
	ppFrameColorsBlackTextOnWhite =0x5        # from enum PpFrameColors
	ppFrameColorsBrowserColors    =0x1        # from enum PpFrameColors
	ppFrameColorsPresentationSchemeAccentColor=0x3        # from enum PpFrameColors
	ppFrameColorsPresentationSchemeTextColor=0x2        # from enum PpFrameColors
	ppFrameColorsWhiteTextOnBlack =0x4        # from enum PpFrameColors
	ppHTMLAutodetect              =0x4        # from enum PpHTMLVersion
	ppHTMLDual                    =0x3        # from enum PpHTMLVersion
	ppHTMLv3                      =0x1        # from enum PpHTMLVersion
	ppHTMLv4                      =0x2        # from enum PpHTMLVersion
	ppIndentControlMixed          =-2         # from enum PpIndentControl
	ppIndentKeepAttr              =0x2        # from enum PpIndentControl
	ppIndentReplaceAttr           =0x1        # from enum PpIndentControl
	ppMediaTypeMixed              =-2         # from enum PpMediaType
	ppMediaTypeMovie              =0x3        # from enum PpMediaType
	ppMediaTypeOther              =0x1        # from enum PpMediaType
	ppMediaTypeSound              =0x2        # from enum PpMediaType
	ppMouseClick                  =0x1        # from enum PpMouseActivation
	ppMouseOver                   =0x2        # from enum PpMouseActivation
	ppBulletAlphaLCParenBoth      =0x8        # from enum PpNumberedBulletStyle
	ppBulletAlphaLCParenRight     =0x9        # from enum PpNumberedBulletStyle
	ppBulletAlphaLCPeriod         =0x0        # from enum PpNumberedBulletStyle
	ppBulletAlphaUCParenBoth      =0xa        # from enum PpNumberedBulletStyle
	ppBulletAlphaUCParenRight     =0xb        # from enum PpNumberedBulletStyle
	ppBulletAlphaUCPeriod         =0x1        # from enum PpNumberedBulletStyle
	ppBulletArabicAbjadDash       =0x18       # from enum PpNumberedBulletStyle
	ppBulletArabicAlphaDash       =0x17       # from enum PpNumberedBulletStyle
	ppBulletArabicDBPeriod        =0x1d       # from enum PpNumberedBulletStyle
	ppBulletArabicDBPlain         =0x1c       # from enum PpNumberedBulletStyle
	ppBulletArabicParenBoth       =0xc        # from enum PpNumberedBulletStyle
	ppBulletArabicParenRight      =0x2        # from enum PpNumberedBulletStyle
	ppBulletArabicPeriod          =0x3        # from enum PpNumberedBulletStyle
	ppBulletArabicPlain           =0xd        # from enum PpNumberedBulletStyle
	ppBulletCircleNumDBPlain      =0x12       # from enum PpNumberedBulletStyle
	ppBulletCircleNumWDBlackPlain =0x14       # from enum PpNumberedBulletStyle
	ppBulletCircleNumWDWhitePlain =0x13       # from enum PpNumberedBulletStyle
	ppBulletHebrewAlphaDash       =0x19       # from enum PpNumberedBulletStyle
	ppBulletHindiAlpha1Period     =0x28       # from enum PpNumberedBulletStyle
	ppBulletHindiAlphaPeriod      =0x24       # from enum PpNumberedBulletStyle
	ppBulletHindiNumParenRight    =0x27       # from enum PpNumberedBulletStyle
	ppBulletHindiNumPeriod        =0x25       # from enum PpNumberedBulletStyle
	ppBulletKanjiKoreanPeriod     =0x1b       # from enum PpNumberedBulletStyle
	ppBulletKanjiKoreanPlain      =0x1a       # from enum PpNumberedBulletStyle
	ppBulletKanjiSimpChinDBPeriod =0x26       # from enum PpNumberedBulletStyle
	ppBulletRomanLCParenBoth      =0x4        # from enum PpNumberedBulletStyle
	ppBulletRomanLCParenRight     =0x5        # from enum PpNumberedBulletStyle
	ppBulletRomanLCPeriod         =0x6        # from enum PpNumberedBulletStyle
	ppBulletRomanUCParenBoth      =0xe        # from enum PpNumberedBulletStyle
	ppBulletRomanUCParenRight     =0xf        # from enum PpNumberedBulletStyle
	ppBulletRomanUCPeriod         =0x7        # from enum PpNumberedBulletStyle
	ppBulletSimpChinPeriod        =0x11       # from enum PpNumberedBulletStyle
	ppBulletSimpChinPlain         =0x10       # from enum PpNumberedBulletStyle
	ppBulletStyleMixed            =-2         # from enum PpNumberedBulletStyle
	ppBulletThaiAlphaParenBoth    =0x20       # from enum PpNumberedBulletStyle
	ppBulletThaiAlphaParenRight   =0x1f       # from enum PpNumberedBulletStyle
	ppBulletThaiAlphaPeriod       =0x1e       # from enum PpNumberedBulletStyle
	ppBulletThaiNumParenBoth      =0x23       # from enum PpNumberedBulletStyle
	ppBulletThaiNumParenRight     =0x22       # from enum PpNumberedBulletStyle
	ppBulletThaiNumPeriod         =0x21       # from enum PpNumberedBulletStyle
	ppBulletTradChinPeriod        =0x16       # from enum PpNumberedBulletStyle
	ppBulletTradChinPlain         =0x15       # from enum PpNumberedBulletStyle
	ppAlignCenter                 =0x2        # from enum PpParagraphAlignment
	ppAlignDistribute             =0x5        # from enum PpParagraphAlignment
	ppAlignJustify                =0x4        # from enum PpParagraphAlignment
	ppAlignJustifyLow             =0x7        # from enum PpParagraphAlignment
	ppAlignLeft                   =0x1        # from enum PpParagraphAlignment
	ppAlignRight                  =0x3        # from enum PpParagraphAlignment
	ppAlignThaiDistribute         =0x6        # from enum PpParagraphAlignment
	ppAlignmentMixed              =-2         # from enum PpParagraphAlignment
	ppPasteBitmap                 =0x1        # from enum PpPasteDataType
	ppPasteDefault                =0x0        # from enum PpPasteDataType
	ppPasteEnhancedMetafile       =0x2        # from enum PpPasteDataType
	ppPasteGIF                    =0x4        # from enum PpPasteDataType
	ppPasteHTML                   =0x8        # from enum PpPasteDataType
	ppPasteJPG                    =0x5        # from enum PpPasteDataType
	ppPasteMetafilePicture        =0x3        # from enum PpPasteDataType
	ppPasteOLEObject              =0xa        # from enum PpPasteDataType
	ppPastePNG                    =0x6        # from enum PpPasteDataType
	ppPasteRTF                    =0x9        # from enum PpPasteDataType
	ppPasteShape                  =0xb        # from enum PpPasteDataType
	ppPasteText                   =0x7        # from enum PpPasteDataType
	ppPlaceholderBitmap           =0x9        # from enum PpPlaceholderType
	ppPlaceholderBody             =0x2        # from enum PpPlaceholderType
	ppPlaceholderCenterTitle      =0x3        # from enum PpPlaceholderType
	ppPlaceholderChart            =0x8        # from enum PpPlaceholderType
	ppPlaceholderDate             =0x10       # from enum PpPlaceholderType
	ppPlaceholderFooter           =0xf        # from enum PpPlaceholderType
	ppPlaceholderHeader           =0xe        # from enum PpPlaceholderType
	ppPlaceholderMediaClip        =0xa        # from enum PpPlaceholderType
	ppPlaceholderMixed            =-2         # from enum PpPlaceholderType
	ppPlaceholderObject           =0x7        # from enum PpPlaceholderType
	ppPlaceholderOrgChart         =0xb        # from enum PpPlaceholderType
	ppPlaceholderPicture          =0x12       # from enum PpPlaceholderType
	ppPlaceholderSlideNumber      =0xd        # from enum PpPlaceholderType
	ppPlaceholderSubtitle         =0x4        # from enum PpPlaceholderType
	ppPlaceholderTable            =0xc        # from enum PpPlaceholderType
	ppPlaceholderTitle            =0x1        # from enum PpPlaceholderType
	ppPlaceholderVerticalBody     =0x6        # from enum PpPlaceholderType
	ppPlaceholderVerticalObject   =0x11       # from enum PpPlaceholderType
	ppPlaceholderVerticalTitle    =0x5        # from enum PpPlaceholderType
	ppPrintBlackAndWhite          =0x2        # from enum PpPrintColorType
	ppPrintColor                  =0x1        # from enum PpPrintColorType
	ppPrintPureBlackAndWhite      =0x3        # from enum PpPrintColorType
	ppPrintHandoutHorizontalFirst =0x2        # from enum PpPrintHandoutOrder
	ppPrintHandoutVerticalFirst   =0x1        # from enum PpPrintHandoutOrder
	ppPrintOutputBuildSlides      =0x7        # from enum PpPrintOutputType
	ppPrintOutputFourSlideHandouts=0x8        # from enum PpPrintOutputType
	ppPrintOutputNineSlideHandouts=0x9        # from enum PpPrintOutputType
	ppPrintOutputNotesPages       =0x5        # from enum PpPrintOutputType
	ppPrintOutputOneSlideHandouts =0xa        # from enum PpPrintOutputType
	ppPrintOutputOutline          =0x6        # from enum PpPrintOutputType
	ppPrintOutputSixSlideHandouts =0x4        # from enum PpPrintOutputType
	ppPrintOutputSlides           =0x1        # from enum PpPrintOutputType
	ppPrintOutputThreeSlideHandouts=0x3        # from enum PpPrintOutputType
	ppPrintOutputTwoSlideHandouts =0x2        # from enum PpPrintOutputType
	ppPrintAll                    =0x1        # from enum PpPrintRangeType
	ppPrintCurrent                =0x3        # from enum PpPrintRangeType
	ppPrintNamedSlideShow         =0x5        # from enum PpPrintRangeType
	ppPrintSelection              =0x2        # from enum PpPrintRangeType
	ppPrintSlideRange             =0x4        # from enum PpPrintRangeType
	ppPublishAll                  =0x1        # from enum PpPublishSourceType
	ppPublishNamedSlideShow       =0x3        # from enum PpPublishSourceType
	ppPublishSlideRange           =0x2        # from enum PpPublishSourceType
	ppRDIAll                      =0x63       # from enum PpRemoveDocInfoType
	ppRDIComments                 =0x1        # from enum PpRemoveDocInfoType
	ppRDIContentType              =0x10       # from enum PpRemoveDocInfoType
	ppRDIDocumentManagementPolicy =0xf        # from enum PpRemoveDocInfoType
	ppRDIDocumentProperties       =0x8        # from enum PpRemoveDocInfoType
	ppRDIDocumentServerProperties =0xe        # from enum PpRemoveDocInfoType
	ppRDIDocumentWorkspace        =0xa        # from enum PpRemoveDocInfoType
	ppRDIInkAnnotations           =0xb        # from enum PpRemoveDocInfoType
	ppRDIPublishPath              =0xd        # from enum PpRemoveDocInfoType
	ppRDIRemovePersonalInformation=0x4        # from enum PpRemoveDocInfoType
	ppRDISlideUpdateInformation   =0x11       # from enum PpRemoveDocInfoType
	ppRevisionInfoBaseline        =0x1        # from enum PpRevisionInfo
	ppRevisionInfoMerged          =0x2        # from enum PpRevisionInfo
	ppRevisionInfoNone            =0x0        # from enum PpRevisionInfo
	ppSaveAsAddIn                 =0x8        # from enum PpSaveAsFileType
	ppSaveAsBMP                   =0x13       # from enum PpSaveAsFileType
	ppSaveAsDefault               =0xb        # from enum PpSaveAsFileType
	ppSaveAsEMF                   =0x17       # from enum PpSaveAsFileType
	ppSaveAsGIF                   =0x10       # from enum PpSaveAsFileType
	ppSaveAsHTML                  =0xc        # from enum PpSaveAsFileType
	ppSaveAsHTMLDual              =0xe        # from enum PpSaveAsFileType
	ppSaveAsHTMLv3                =0xd        # from enum PpSaveAsFileType
	ppSaveAsJPG                   =0x11       # from enum PpSaveAsFileType
	ppSaveAsMetaFile              =0xf        # from enum PpSaveAsFileType
	ppSaveAsOpenXMLAddin          =0x1e       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLPresentation   =0x18       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLPresentationMacroEnabled=0x19       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLShow           =0x1c       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLShowMacroEnabled=0x1d       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLTemplate       =0x1a       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLTemplateMacroEnabled=0x1b       # from enum PpSaveAsFileType
	ppSaveAsOpenXMLTheme          =0x1f       # from enum PpSaveAsFileType
	ppSaveAsPDF                   =0x20       # from enum PpSaveAsFileType
	ppSaveAsPNG                   =0x12       # from enum PpSaveAsFileType
	ppSaveAsPowerPoint3           =0x4        # from enum PpSaveAsFileType
	ppSaveAsPowerPoint4           =0x3        # from enum PpSaveAsFileType
	ppSaveAsPowerPoint4FarEast    =0xa        # from enum PpSaveAsFileType
	ppSaveAsPowerPoint7           =0x2        # from enum PpSaveAsFileType
	ppSaveAsPresForReview         =0x16       # from enum PpSaveAsFileType
	ppSaveAsPresentation          =0x1        # from enum PpSaveAsFileType
	ppSaveAsRTF                   =0x6        # from enum PpSaveAsFileType
	ppSaveAsShow                  =0x7        # from enum PpSaveAsFileType
	ppSaveAsTIF                   =0x15       # from enum PpSaveAsFileType
	ppSaveAsTemplate              =0x5        # from enum PpSaveAsFileType
	ppSaveAsWebArchive            =0x14       # from enum PpSaveAsFileType
	ppSaveAsXMLPresentation       =0x22       # from enum PpSaveAsFileType
	ppSaveAsXPS                   =0x21       # from enum PpSaveAsFileType
	ppSelectionNone               =0x0        # from enum PpSelectionType
	ppSelectionShapes             =0x2        # from enum PpSelectionType
	ppSelectionSlides             =0x1        # from enum PpSelectionType
	ppSelectionText               =0x3        # from enum PpSelectionType
	ppShapeFormatBMP              =0x3        # from enum PpShapeFormat
	ppShapeFormatEMF              =0x5        # from enum PpShapeFormat
	ppShapeFormatGIF              =0x0        # from enum PpShapeFormat
	ppShapeFormatJPG              =0x1        # from enum PpShapeFormat
	ppShapeFormatPNG              =0x2        # from enum PpShapeFormat
	ppShapeFormatWMF              =0x4        # from enum PpShapeFormat
	ppLayoutBlank                 =0xc        # from enum PpSlideLayout
	ppLayoutChart                 =0x8        # from enum PpSlideLayout
	ppLayoutChartAndText          =0x6        # from enum PpSlideLayout
	ppLayoutClipArtAndVerticalText=0x1a       # from enum PpSlideLayout
	ppLayoutClipartAndText        =0xa        # from enum PpSlideLayout
	ppLayoutComparison            =0x22       # from enum PpSlideLayout
	ppLayoutContentWithCaption    =0x23       # from enum PpSlideLayout
	ppLayoutCustom                =0x20       # from enum PpSlideLayout
	ppLayoutFourObjects           =0x18       # from enum PpSlideLayout
	ppLayoutLargeObject           =0xf        # from enum PpSlideLayout
	ppLayoutMediaClipAndText      =0x12       # from enum PpSlideLayout
	ppLayoutMixed                 =-2         # from enum PpSlideLayout
	ppLayoutObject                =0x10       # from enum PpSlideLayout
	ppLayoutObjectAndText         =0xe        # from enum PpSlideLayout
	ppLayoutObjectAndTwoObjects   =0x1e       # from enum PpSlideLayout
	ppLayoutObjectOverText        =0x13       # from enum PpSlideLayout
	ppLayoutOrgchart              =0x7        # from enum PpSlideLayout
	ppLayoutPictureWithCaption    =0x24       # from enum PpSlideLayout
	ppLayoutSectionHeader         =0x21       # from enum PpSlideLayout
	ppLayoutTable                 =0x4        # from enum PpSlideLayout
	ppLayoutText                  =0x2        # from enum PpSlideLayout
	ppLayoutTextAndChart          =0x5        # from enum PpSlideLayout
	ppLayoutTextAndClipart        =0x9        # from enum PpSlideLayout
	ppLayoutTextAndMediaClip      =0x11       # from enum PpSlideLayout
	ppLayoutTextAndObject         =0xd        # from enum PpSlideLayout
	ppLayoutTextAndTwoObjects     =0x15       # from enum PpSlideLayout
	ppLayoutTextOverObject        =0x14       # from enum PpSlideLayout
	ppLayoutTitle                 =0x1        # from enum PpSlideLayout
	ppLayoutTitleOnly             =0xb        # from enum PpSlideLayout
	ppLayoutTwoColumnText         =0x3        # from enum PpSlideLayout
	ppLayoutTwoObjects            =0x1d       # from enum PpSlideLayout
	ppLayoutTwoObjectsAndObject   =0x1f       # from enum PpSlideLayout
	ppLayoutTwoObjectsAndText     =0x16       # from enum PpSlideLayout
	ppLayoutTwoObjectsOverText    =0x17       # from enum PpSlideLayout
	ppLayoutVerticalText          =0x19       # from enum PpSlideLayout
	ppLayoutVerticalTitleAndText  =0x1b       # from enum PpSlideLayout
	ppLayoutVerticalTitleAndTextOverChart=0x1c       # from enum PpSlideLayout
	ppSlideShowManualAdvance      =0x1        # from enum PpSlideShowAdvanceMode
	ppSlideShowRehearseNewTimings =0x3        # from enum PpSlideShowAdvanceMode
	ppSlideShowUseSlideTimings    =0x2        # from enum PpSlideShowAdvanceMode
	ppSlideShowPointerAlwaysHidden=0x3        # from enum PpSlideShowPointerType
	ppSlideShowPointerArrow       =0x1        # from enum PpSlideShowPointerType
	ppSlideShowPointerAutoArrow   =0x4        # from enum PpSlideShowPointerType
	ppSlideShowPointerEraser      =0x5        # from enum PpSlideShowPointerType
	ppSlideShowPointerNone        =0x0        # from enum PpSlideShowPointerType
	ppSlideShowPointerPen         =0x2        # from enum PpSlideShowPointerType
	ppShowAll                     =0x1        # from enum PpSlideShowRangeType
	ppShowNamedSlideShow          =0x3        # from enum PpSlideShowRangeType
	ppShowSlideRange              =0x2        # from enum PpSlideShowRangeType
	ppSlideShowBlackScreen        =0x3        # from enum PpSlideShowState
	ppSlideShowDone               =0x5        # from enum PpSlideShowState
	ppSlideShowPaused             =0x2        # from enum PpSlideShowState
	ppSlideShowRunning            =0x1        # from enum PpSlideShowState
	ppSlideShowWhiteScreen        =0x4        # from enum PpSlideShowState
	ppShowTypeKiosk               =0x3        # from enum PpSlideShowType
	ppShowTypeSpeaker             =0x1        # from enum PpSlideShowType
	ppShowTypeWindow              =0x2        # from enum PpSlideShowType
	ppSlideSize35MM               =0x4        # from enum PpSlideSizeType
	ppSlideSizeA3Paper            =0x9        # from enum PpSlideSizeType
	ppSlideSizeA4Paper            =0x3        # from enum PpSlideSizeType
	ppSlideSizeB4ISOPaper         =0xa        # from enum PpSlideSizeType
	ppSlideSizeB4JISPaper         =0xc        # from enum PpSlideSizeType
	ppSlideSizeB5ISOPaper         =0xb        # from enum PpSlideSizeType
	ppSlideSizeB5JISPaper         =0xd        # from enum PpSlideSizeType
	ppSlideSizeBanner             =0x6        # from enum PpSlideSizeType
	ppSlideSizeCustom             =0x7        # from enum PpSlideSizeType
	ppSlideSizeHagakiCard         =0xe        # from enum PpSlideSizeType
	ppSlideSizeLedgerPaper        =0x8        # from enum PpSlideSizeType
	ppSlideSizeLetterPaper        =0x2        # from enum PpSlideSizeType
	ppSlideSizeOnScreen           =0x1        # from enum PpSlideSizeType
	ppSlideSizeOnScreen16x10      =0x10       # from enum PpSlideSizeType
	ppSlideSizeOnScreen16x9       =0xf        # from enum PpSlideSizeType
	ppSlideSizeOverhead           =0x5        # from enum PpSlideSizeType
	ppSoundEffectsMixed           =-2         # from enum PpSoundEffectType
	ppSoundFile                   =0x2        # from enum PpSoundEffectType
	ppSoundNone                   =0x0        # from enum PpSoundEffectType
	ppSoundStopPrevious           =0x1        # from enum PpSoundEffectType
	ppSoundFormatCDAudio          =0x3        # from enum PpSoundFormatType
	ppSoundFormatMIDI             =0x2        # from enum PpSoundFormatType
	ppSoundFormatMixed            =-2         # from enum PpSoundFormatType
	ppSoundFormatNone             =0x0        # from enum PpSoundFormatType
	ppSoundFormatWAV              =0x1        # from enum PpSoundFormatType
	ppTabStopCenter               =0x2        # from enum PpTabStopType
	ppTabStopDecimal              =0x4        # from enum PpTabStopType
	ppTabStopLeft                 =0x1        # from enum PpTabStopType
	ppTabStopMixed                =-2         # from enum PpTabStopType
	ppTabStopRight                =0x3        # from enum PpTabStopType
	ppAnimateByAllLevels          =0x10       # from enum PpTextLevelEffect
	ppAnimateByFifthLevel         =0x5        # from enum PpTextLevelEffect
	ppAnimateByFirstLevel         =0x1        # from enum PpTextLevelEffect
	ppAnimateByFourthLevel        =0x4        # from enum PpTextLevelEffect
	ppAnimateBySecondLevel        =0x2        # from enum PpTextLevelEffect
	ppAnimateByThirdLevel         =0x3        # from enum PpTextLevelEffect
	ppAnimateLevelMixed           =-2         # from enum PpTextLevelEffect
	ppAnimateLevelNone            =0x0        # from enum PpTextLevelEffect
	ppBodyStyle                   =0x3        # from enum PpTextStyleType
	ppDefaultStyle                =0x1        # from enum PpTextStyleType
	ppTitleStyle                  =0x2        # from enum PpTextStyleType
	ppAnimateByCharacter          =0x2        # from enum PpTextUnitEffect
	ppAnimateByParagraph          =0x0        # from enum PpTextUnitEffect
	ppAnimateByWord               =0x1        # from enum PpTextUnitEffect
	ppAnimateUnitMixed            =-2         # from enum PpTextUnitEffect
	ppTransitionSpeedFast         =0x3        # from enum PpTransitionSpeed
	ppTransitionSpeedMedium       =0x2        # from enum PpTransitionSpeed
	ppTransitionSpeedMixed        =-2         # from enum PpTransitionSpeed
	ppTransitionSpeedSlow         =0x1        # from enum PpTransitionSpeed
	ppUpdateOptionAutomatic       =0x2        # from enum PpUpdateOption
	ppUpdateOptionManual          =0x1        # from enum PpUpdateOption
	ppUpdateOptionMixed           =-2         # from enum PpUpdateOption
	ppViewHandoutMaster           =0x4        # from enum PpViewType
	ppViewMasterThumbnails        =0xc        # from enum PpViewType
	ppViewNormal                  =0x9        # from enum PpViewType
	ppViewNotesMaster             =0x5        # from enum PpViewType
	ppViewNotesPage               =0x3        # from enum PpViewType
	ppViewOutline                 =0x6        # from enum PpViewType
	ppViewPrintPreview            =0xa        # from enum PpViewType
	ppViewSlide                   =0x1        # from enum PpViewType
	ppViewSlideMaster             =0x2        # from enum PpViewType
	ppViewSlideSorter             =0x7        # from enum PpViewType
	ppViewThumbnails              =0xb        # from enum PpViewType
	ppViewTitleMaster             =0x8        # from enum PpViewType
	ppWindowMaximized             =0x3        # from enum PpWindowState
	ppWindowMinimized             =0x2        # from enum PpWindowState
	ppWindowNormal                =0x1        # from enum PpWindowState

